### PR TITLE
TECH Fix issue with multiple handlers

### LINKED ISSUE #1: Doesn't work properly with more than one handler
Samuel Rossille 
[9:43 PM] 
@louis.ledey @tmarcon j'ai sorti la partie "worker" de pidget dans un projet à part, mais du coup en la relisant, j'ai l'impression qu'il y a la même erreur que celle qui a été faite et corrigée dans chrp-worker, sur les cles de routing multiples bindées sur la même queue: https://github.com/transcovo/go-chpr-worker/blob/871d4afe893208595854061ebbbfe7f6ea591a65/worker.go#L222

Louis Ledey
[9:45 PM] 
Ouais c'est ce que je t'avais dit à l'oral, il faut le corriger

### PR DESCRIPTION
**Pull request by vayan**
Creates a new channel and queue for each routing key/handler.

The generated queue name for each comsumer is following the format "queueName.RoutingKey"

Also update README 👍 

Fix #1

### CODE REVIEW

File: worker.go [hunk 1]
```diff
@@ -213,18 +210,22 @@ func (worker *AmqpWorker) Start(signals <-chan os.Signal) {
...
 
-	queue := declareQueue(channel.QueueDeclare, worker.Queue, nil)
+		declareExchange(channel.ExchangeDeclare, worker.Exchange)
 
-	setChannelQos(channel.Qos, worker.ChannelPrefetchCount)
+		setChannelQos(channel.Qos, worker.ChannelPrefetchCount)
 
-	for _, handler := range worker.Handlers {
-		bindQueue(channel.QueueBind, worker.Exchange, queue.Name, handler.RoutingKey)
+		declareQueue(channel.QueueDeclare, formattedQueueName, nil)
```
Comment (Kelvyne) [inline worker.go:222]: These functions can actually fail and will panic. Maybe it is time to remove these panic and handle the errors cleanly ? If one handler fails to initialize, close previously opened ressources ?

**Review by Kelvyne — APPROVED** [review]
LGTM
